#include QMK_KEYBOARD_H
#include "sm_td.h"


// Home row mods using SM_TD
// Mac modifiers: GUI=Command, ALT=Option, CTRL=Control
smtd_resolution on_smtd_action(uint16_t keycode, smtd_action action, uint8_t tap_count) {
    switch (keycode) {
        // Left hand home row mods (Colemak DH positions)
        SMTD_MT(KC_A, KC_LGUI)   // A -> Command (GUI)
        SMTD_MT(KC_R, KC_LALT)   // R -> Option (ALT)
        SMTD_MT(KC_S, KC_LCTL)   // S -> Control
        SMTD_MT(KC_T, KC_LSFT)   // T -> Shift
        
        // Right hand home row mods (Colemak DH positions)
        SMTD_MT(KC_N, KC_LSFT)   // N -> Shift
        SMTD_MT(KC_E, KC_LCTL)   // E -> Control
        SMTD_MT(KC_I, KC_LALT)   // I -> Option (ALT)
        SMTD_MT(KC_O, KC_LGUI)   // O -> Command (GUI)
    }
    return SMTD_RESOLUTION_UNHANDLED;
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ,-----------------------------------------.                ,-----------------------------------------.
 * |      |  Q   |  W   |  F   |  P   |  B   |                |  J   |  L   |  U   |  Y   | SCLN |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |  A   |  R   |  S   |  T   |  G   |                |  M   |  N   |  E   |  I   |  O   |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |  Z   |  X   |  C   |  D   |  V   |                |  K   |  H   | COMM | DOT  | SLSH |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 *                             | ESC  | BSPC | TAB  |  | ENT  | SPC  | DEL  |
 *                             `--------------------'  `--------------------'
 *                                                                               generated by [keymapviz] */
    [0] = LAYOUT_split_3x6_3(
        KC_NO,   KC_Q,    KC_W,    KC_F,    KC_P,    KC_B,         KC_J,    KC_L,    KC_U,    KC_Y,    KC_SCLN, KC_NO,
        KC_NO,   KC_A,    KC_R,    KC_S,    KC_T,    KC_G,         KC_M,    KC_N,    KC_E,    KC_I,    KC_O,    KC_NO,
        KC_NO,   KC_Z,    KC_X,    KC_C,    KC_D,    KC_V,         KC_K,    KC_H,    KC_COMM, KC_DOT,  KC_SLSH, KC_NO,
                          KC_ESC,  KC_BSPC,  KC_TAB,      KC_ENT,  KC_SPC,  KC_DEL
    ),
};

