COMBO_ENABLE = yes
SEND_STRING_ENABLE = yes
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
RGB_MATRIX_ENABLE = no
KEY_OVERRIDE_ENABLE = yes

# Disable some features to reduce firmware size
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no